print('Hello World')
print('hi')
print("studytonight is a group")
print("studytonight","is","a","group")
print("studying", end ='')
print("is good")
print('studying', end=' ')
print('is good for',end="_")
print('us')
print('studying is good')
print('Us')
